spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teamfresh?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: teamfresh
    password: Teamfresh12!!
    hikari:
      maximum-pool-size: 20

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8085
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false
